name: 1.0$(rev:.r) # build numbering format

resources:
  repositories:
  - repository: ALMStuff
    type: github
    name: DrMueller/ALMStuff
    ref: refs/heads/master
    endpoint: GitHub-DrMueller

jobs:
- job: 'BuildAndPublishAsArtifact'
  displayName: 'Build and save zipped Artifact'
  pool:
    name: 'Hosted VS2017'
  steps:
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '**/*.csproj'
      vstsFeed: '3c2d9c9a-d8f7-42f4-b7a3-dddf4064110a'
      verbosityRestore: Diagnostic

  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      projects: '**/*.csproj'
      arguments: '--configuration Release'
    
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish

      publishWebProjects: false

      projects: '**/*.csproj'

      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory) /p:DeleteExistingFiles=True'

      zipAfterPublish: false

      modifyOutputPath: false

  - template: AzureDevOps/BuildTemplates/NetCore/Steps/Zip_And_Save_Artifact.yaml@ALMStuff
